# Please see https://www.getzola.org/documentation/getting-started/configuration/

base_url = "https://eldred.fr"
title = "ISSOtm's warehouse"
description = "ISSOtm's personal website; contains a lot of prose around programming, especially the Game Boy."
default_language = "en"

taxonomies = [
	{ name = "tags", feed = true },
]

compile_sass = true
minify_html = true
generate_feed = true
feed_filename = "rss.xml"
build_search_index = true

[markdown]
highlight_code = true
extra_syntaxes_and_themes = [ "sublime-rgbds/ASM" ]
highlight_theme = "css"
highlight_themes_css = [
	{ theme = "gruvbox-dark", filename = "syntax-theme-dark.css" },
	{ theme = "gruvbox-light", filename = "syntax-theme-light.css" },
]
smart_punctuation = true
